### ISSUE TITLE
Upgrade urllib3 to version

### ISSUE THREAD

**Issue by lmperry** [flywheel-apps/hcp-struct#6]
Remediation
Upgrade urllib3 to version 1.24.2 or later. For example:

urllib3>=1.24.2

https://github.com/flywheel-apps/hcp-struct/network/alert/requirements.txt/urllib3/open

**Comment by joshicola** [comment]
In requirements.txt.

Test Pending.

**Comment by joshicola** [comment]
the requirements.txt line needs to be:
urllib3>=1.24.2,<1.25

otherwise the "requests" package breaks.

"dry-run" passed.

**Comment by joshicola** [comment]
Test Passed.
Closing.
